application: go-code
version: 1
runtime: go
api_version: go1

handlers:
- url: /images/
  static_dir: images
  
- url: /css/
  static_dir: css
  
- url: /js/
  static_dir: js
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: _go_app
